apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: skills-svc
  namespace: skills
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: app-v1
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: skills-svc.skills.svc.cluster.local