apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: deploy-security-group-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: deploy
  securityGroups:
    groupIds:
      - sg-092b39f577b9c45fa