apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: skills-cluster
  version: "1.27"
  region: ap-northeast-2
  tags:
    karpenter.sh/discovery: skills-cluster

karpenter:
  version: 'v0.29.2'
  createServiceAccount: true
  withSpotInterruptionQueue: true

vpc:
  subnets:
    private:
      private-a: { id: subnet-098c9f50ea1ba367b }
      private-b: { id: subnet-0f314819465c62610 }
      private-c: { id: subnet-028dcf7dac4effdb1 }

iamIdentityMappings:
  - arn: arn:aws:iam::532003114460:role/AdministratorAccess
    groups:
      - system:master
    username: admin
    noDuplicateARNs: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]


iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: appmesh-controller
      namespace: appmesh-system
    attachPolicyARNs:
      - "arn:aws:iam::aws:policy/AWSCloudMapFullAccess"
      - "arn:aws:iam::aws:policy/AWSAppMeshFullAccess"
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true

managedNodeGroups:
  - name: skills-addon-ng
    labels: { skills/dedicated: addon }
    instanceType: c5.large
    instanceName: skills-addon-ng
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
    privateNetworking: true
    volumeType: gp2
    volumeEncrypted: true
    taints:
      - key: "Management"
        value: "Addons"
        effect: "NoSchedule"
    subnets:
      - private-a
      - private-b
      - private-c

  - name: skills-app-ng
    labels: { skills/dedicated: app }
    instanceType: c5.large
    instanceName: skills-app-ng
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
    privateNetworking: true
    volumeType: gp2
    volumeEncrypted: true
    subnets:
      - private-a
      - private-b
      - private-c