apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-1
  namespace: default
  labels:
    app.kubernetes.io/name: app-v1
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-2
  namespace: default
  labels:
    apps: app-v2
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      apps: app-v2
  template:
    metadata:
      labels:
        apps: app-v2
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80