apiVersion: apps/v1
kind: Deployment
metadata:
  name: value-test
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: ENV3
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: ENV2