apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteMany, ReadOnlyMany 
  resources:
    requests:
      storage: 2Gi
  storageClassName: ebs-sc