apiVersion: v1
kind: Service
metadata:
  name: skills-svc
  namespace: skills
  labels:
    app.kubernetes.io/name: app-v1
spec:
  selector:
    app.kubernetes.io/name: app-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skills
  namespace: skills
  labels:
    app.kubernetes.io/name: app-v1
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-v1
    spec:
      serviceAccountName: envoy-proxy
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80