apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: nginx-vol
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: nginx-vol
      configMap:
        name: nginx-config
        items:
          - key: index.html
            path: index.html